CREATE DATABASE M_InLock;
USE M_InLock;

CREATE TABLE Usuarios(
	UsuarioId INT PRIMARY KEY IDENTITY,
	Email VARCHAR (100) NOT NULL UNIQUE, 
	Senha VARCHAR (100) NOT NULL,
	PermissaoUsuario VARCHAR(50)
);
CREATE TABLE Estudios(
	EstudioId INT PRIMARY KEY IDENTITY,
	NomeEstudio VARCHAR (100) NOT NULL UNIQUE, 
	PaisOrigem VARCHAR (100) NOT NULL,
	DataCriacao DATE NOT NULL,
	UsuarioId INT FOREIGN KEY REFERENCES Usuarios (UsuarioId)
);

CREATE TABLE Jogos(
	JogoId INT PRIMARY KEY IDENTITY,
	NomeJogo VARCHAR (100) NOT NULL, 
	Descricao VARCHAR (500) NOT NULL,
	DataLancamento DATE NOT NULL,
	Valor VARCHAR (50) NOT NULL,
	EstudioId INT FOREIGN KEY REFERENCES Estudios (EstudioId)
);
